"""empty message

Revision ID: 0bd917e846a1
Revises: 1fc0b25cace9
Create Date: 2017-08-15 19:25:47.823636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bd917e846a1'
down_revision = '1fc0b25cace9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olx', sa.Column('adcode', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('ads', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('city', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('day', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('description', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('image_urls', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('main_category', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('main_image_urls', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('month', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('name', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('novo_usado', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('price', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('sub_category', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('suburb', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('time', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('title', sa.String(), nullable=True))
    op.add_column('olx', sa.Column('zipcode', sa.String(), nullable=True))
    op.drop_column('olx', 'url')
    op.drop_column('olx', 'result_no_stop_words')
    op.drop_column('olx', 'result_all')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olx', sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('olx', sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('olx', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('olx', 'zipcode')
    op.drop_column('olx', 'title')
    op.drop_column('olx', 'time')
    op.drop_column('olx', 'suburb')
    op.drop_column('olx', 'sub_category')
    op.drop_column('olx', 'price')
    op.drop_column('olx', 'phone_number')
    op.drop_column('olx', 'phone')
    op.drop_column('olx', 'novo_usado')
    op.drop_column('olx', 'name')
    op.drop_column('olx', 'month')
    op.drop_column('olx', 'main_image_urls')
    op.drop_column('olx', 'main_category')
    op.drop_column('olx', 'image_urls')
    op.drop_column('olx', 'description')
    op.drop_column('olx', 'day')
    op.drop_column('olx', 'city')
    op.drop_column('olx', 'ads')
    op.drop_column('olx', 'adcode')
    # ### end Alembic commands ###
